import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Linking,
  Platform,
  Alert,
} from 'react-native';
import * as Clipboard from 'expo-clipboard';
import { SafeAreaView } from 'react-native-safe-area-context';
import * as Haptics from 'expo-haptics';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { RouteProp } from '@react-navigation/native';
import { RootStackParamList } from '../types';
import { colors, spacing, fontSize, radius } from '../theme';

type Props = {
  navigation: NativeStackNavigationProp<RootStackParamList, 'TakeDown'>;
  route: RouteProp<RootStackParamList, 'TakeDown'>;
};

interface Channel {
  icon: string;
  name: string;
  description: string;
  getUrl: (appName: string, packageId: string, report: string) => string;
  iosOnly?: boolean;
}

const CHANNELS: Channel[] = [
  {
    icon: '🔴',
    name: 'Google Play Store',
    description: 'Flag as inappropriate on the app listing. Fastest signal to Google.',
    getUrl: (_, packageId) =>
      `https://play.google.com/store/apps/details?id=${packageId || ''}`,
  },
  {
    icon: '📧',
    name: 'CERT-In',
    description: 'Government lever — can compel takedown from Indian infrastructure.',
    getUrl: (appName, _, report) =>
      `mailto:incident@cert-in.org.in?subject=${encodeURIComponent(
        `Scam App Report: ${appName}`,
      )}&body=${encodeURIComponent(report)}`,
  },
  {
    icon: '🌐',
    name: 'National Cyber Crime Portal',
    description: 'File a complaint, especially if money was lost.',
    getUrl: () => 'https://cybercrime.gov.in',
  },
  {
    icon: '🏦',
    name: 'RBI Sachet Portal',
    description: 'For unauthorised lending apps — direct escalation to RBI.',
    getUrl: () => 'https://sachet.rbi.org.in',
  },
  {
    icon: '🍎',
    name: 'Apple App Store',
    description: 'Report to Apple Support if this app is also on iOS.',
    getUrl: () => 'https://support.apple.com/en-us/HT209396',
  },
];

export default function TakeDownScreen({ navigation, route }: Props) {
  const { result } = route.params;
  const topSignals = result.firedSignals.slice(0, 5);

  const report = [
    'SCAM APP REPORT',
    `App: ${result.appName}`,
    `Package: ${result.packageId || 'Unknown'}`,
    `Risk Score: ${result.score}/100 (${result.verdictLabel})`,
    `RBI Status: ${result.gateBanner}`,
    '',
    'Issues identified:',
    ...topSignals.map((s) => `• ${s.name}`),
    '',
    'I am requesting immediate review and removal of this app to protect users.',
    '',
    'Generated by ScamShield (scamshield.ai)',
  ].join('\n');

  const handleCopy = async () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    await Clipboard.setStringAsync(report);
    Alert.alert('Copied', 'Report copied to clipboard. Paste it into your complaint.');
  };

  const handleOpen = (channel: Channel) => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    const url = channel.getUrl(result.appName, result.packageId || '', report);
    Linking.canOpenURL(url).then((can) => {
      if (can) Linking.openURL(url);
    });
  };

  return (
    <SafeAreaView style={styles.safe} edges={['top', 'bottom']}>
      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}
      >
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity style={styles.backBtn} onPress={() => navigation.goBack()}>
            <Text style={styles.backText}>← Back</Text>
          </TouchableOpacity>
          <Text style={styles.title}>Help Take This App Down</Text>
          <Text style={styles.subtitle}>
            Parallel reports speed up removal. Attach your complaint PDF and screenshots.
          </Text>
        </View>

        {/* Report template */}
        <View style={styles.reportCard}>
          <View style={styles.reportCardHeader}>
            <Text style={styles.reportCardTitle}>Report Template</Text>
            <TouchableOpacity
              style={styles.copyBtn}
              onPress={handleCopy}
              activeOpacity={0.8}
            >
              <Text style={styles.copyBtnText}>Copy Report</Text>
            </TouchableOpacity>
          </View>
          <ScrollView
            style={styles.reportScroll}
            nestedScrollEnabled
            showsVerticalScrollIndicator
          >
            <Text style={styles.reportText} selectable>{report}</Text>
          </ScrollView>
        </View>

        {/* Report channels */}
        <Text style={styles.channelsTitle}>Report Channels</Text>
        <Text style={styles.channelsSubtitle}>Ordered by leverage. Report to all for maximum impact.</Text>

        {CHANNELS.map((channel) => (
          <View key={channel.name} style={styles.channelCard}>
            <View style={styles.channelLeft}>
              <Text style={styles.channelIcon}>{channel.icon}</Text>
            </View>
            <View style={styles.channelInfo}>
              <Text style={styles.channelName}>{channel.name}</Text>
              <Text style={styles.channelDesc}>{channel.description}</Text>
            </View>
            <TouchableOpacity
              style={styles.openBtn}
              onPress={() => handleOpen(channel)}
              activeOpacity={0.8}
            >
              <Text style={styles.openBtnText}>Open →</Text>
            </TouchableOpacity>
          </View>
        ))}

        {/* Tip box */}
        <View style={styles.tipBox}>
          <Text style={styles.tipText}>
            💡 Parallel reports from multiple users dramatically speed up removal. Share this report with other victims.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingBottom: spacing.xxl,
  },
  header: {
    padding: spacing.md,
    paddingBottom: spacing.lg,
  },
  backBtn: {
    marginBottom: spacing.md,
  },
  backText: {
    color: colors.primary,
    fontSize: fontSize.md,
    fontWeight: '600',
  },
  title: {
    fontSize: fontSize.xxxl,
    fontWeight: '800',
    color: colors.textPrimary,
    letterSpacing: -0.5,
    marginBottom: spacing.sm,
  },
  subtitle: {
    fontSize: fontSize.md,
    color: colors.textSecondary,
    lineHeight: 22,
  },
  reportCard: {
    marginHorizontal: spacing.md,
    backgroundColor: colors.bgCard,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.xl,
    overflow: 'hidden',
  },
  reportCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  reportCardTitle: {
    fontSize: fontSize.md,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  copyBtn: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs + 2,
    borderRadius: radius.full,
  },
  copyBtnText: {
    color: '#FFFFFF',
    fontSize: fontSize.sm,
    fontWeight: '700',
  },
  reportScroll: {
    maxHeight: 200,
    padding: spacing.md,
  },
  reportText: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    lineHeight: 20,
  },
  channelsTitle: {
    fontSize: fontSize.xl,
    fontWeight: '800',
    color: colors.textPrimary,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.xs,
    letterSpacing: -0.3,
  },
  channelsSubtitle: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.md,
  },
  channelCard: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: spacing.md,
    marginBottom: spacing.sm,
    backgroundColor: colors.bgCard,
    borderRadius: radius.lg,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    gap: spacing.sm,
  },
  channelLeft: {
    width: 40,
    alignItems: 'center',
    flexShrink: 0,
  },
  channelIcon: {
    fontSize: 24,
  },
  channelInfo: {
    flex: 1,
  },
  channelName: {
    fontSize: fontSize.md,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 3,
  },
  channelDesc: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
    lineHeight: 18,
  },
  openBtn: {
    backgroundColor: '#6366F115',
    borderRadius: radius.md,
    paddingHorizontal: spacing.sm + 4,
    paddingVertical: spacing.xs + 2,
    borderWidth: 1,
    borderColor: '#6366F130',
    flexShrink: 0,
  },
  openBtnText: {
    color: colors.primaryLight,
    fontSize: fontSize.sm,
    fontWeight: '700',
  },
  tipBox: {
    marginHorizontal: spacing.md,
    marginTop: spacing.md,
    backgroundColor: '#F59E0B10',
    borderRadius: radius.lg,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: '#F59E0B30',
  },
  tipText: {
    fontSize: fontSize.sm,
    color: colors.caution,
    lineHeight: 20,
  },
});
